# Generated by Django 5.1.1 on 2024-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustom',
            name='avatar',
            field=models.ImageField(default='default/noimage.jpg', upload_to='images/avatars/'),
        ),
    ]
