# Generated by Django 5.1.1 on 2024-09-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Lời nhắn'),
        ),
    ]
