# Generated by Django 5.1.1 on 2024-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_remove_blog_tags_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
